### ISSUE TITLE
Random com.google.cloud.storage.StorageException: Socket closed

### ISSUE THREAD

**Issue by ewirch** [googleapis/google-cloud-java#4162]
We randomly receive `com.google.cloud.storage.StorageException: Socket closed` when uploading files.

#### Environment details

- OS: Ubuntu 16
- Java version: 11
- google-cloud-java version(s): google-cloud-storage 1.53.0

#### Stacktrace

```
com.google.cloud.storage.StorageException: Socket closed
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:704)
        at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
        at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:47)
        at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:161)
        ....
Caused by: javax.net.ssl.SSLProtocolException: Socket closed
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:143)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1011)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:685)
        ... 105 common frames omitted
Caused by: java.net.SocketException: Socket closed
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
        ... 119 common frames omitted
```

Can you add `SocketException` to retryable exceptions? Or any hints how to diagnose the root cause?

**Comment by chingor13** [comment]
Thanks for reporting this.

Can you give us a bit more information:
* Is this running from GCP or externally?
* Is the upload succeeding?
* Is there a specific file size where you see this happening? (very large files, very small files)

**Comment by ewirch** [comment]
> GCP or externally?

Running on GCE.

> Is the upload succeeding?

Unfortunately I can't tell. Have to increase diagnostic logging.

> Is there a specific file size where you see this happening? (very large files, very small files)

Can't tell as well. All the files have a size of 10-20kB. Not very large, not very small.

A network problem is unlikely. There were multiple requests running in parallel, and only one failed.

**Comment by ewirch** [comment]
Looking at the GCS load chart, there were request count peaks where we received the errors.

Once
ReadObject: 48/s
WriteObject: 25/s

another time:
GetObjectMetadata: 56/s
ReadObject: 56/s
WriteObject: 30/s

**Comment by jontejj** [comment]
We are seeing these as well, we are using version 1.5.0 of google-cloud-storage though. We are trying to write about 100 files at the same time.

**Comment by jontejj** [comment]
Funnily enough, we are also using java 11 :)

**Comment by jontejj** [comment]
I was able to reproduce this on jdk 11 (but it seems to work on jdk 8)

Here's pseudo code for the test:
```
        ConcurrencyTester.verify(new RunnableFactory() {

            @Override
            public int iterationCount() {
                return 10;
            }

            @Override
            public Runnable create(int uniqueNumber) {
                return () -> {
                    Path helloFile = Paths.get("hello", "" + uniqueNumber);
                    try {
                        byte[] DATA = ("helloWorld" + uniqueNumber).getBytes();
                        storageRoot.write(DATA, helloFile, "application/octet-stream", CacheControl.DEFAULT);
                        byte[] readData = storageRoot.readFully(helloFile);
                        assertThat(readData).as("read bytes did not match written bytes").isEqualTo(DATA);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                };
            }
        }, 60, TimeUnit.SECONDS);
```

**Comment by jontejj** [comment]
I can't reproduce it with 1.59.0 of google-cloud-storage, so the bug seems to have been fixed.

**Comment by ajaaym** [comment]
closing this as it seems fixed.

**Comment by nelivdim8** [comment]
Hello,

I am still receiving this error. Is there a possibility that the issue is not fully resolved?
```
com.google.cloud.storage.StorageException: Socket closed
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:219)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:702)
        at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
        at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:47)

Caused by: java.net.SocketException: Socket closed
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
        ... 186 more
```
Thanks in advance!
