### ISSUE TITLE
Storage integration test failing in nightly since Dec. 21

### ISSUE THREAD

**Issue by bmccutchon** [googleapis/google-cloud-java#4265]
Nightly link: https://source.cloud.google.com/results/invocations/fd413181-7414-4e8e-9d62-13cfd8fe7a7d/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fstorage-it/log

**Comment by ajaaym** [comment]
Fixed in [4266](https://github.com/googleapis/google-cloud-java/pull/4266)

**Comment by frankyn** [comment]
Hi all, 

This is a bug in the GCS service and one the TL's is now aware of it. 

I'm reopening this issue as it didn't resolve the underlying issue raised.

Internal bug: 122739863

**Comment by andrey-qlogic** [comment]
@frankyn 
Nightly link says one test is failed 
**testRotateFromCustomerEncryptionToKmsKeyWithCustomerEncryption** 

https://source.cloud.google.com/results/invocations/fd413181-7414-4e8e-9d62-13cfd8fe7a7d/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fstorage-it/log

which has to be is ignored

https://github.com/googleapis/google-cloud-java/blob/2aa9d803ed532d91a5f430368f1ec4fd21f3dd24/google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java#L1276

**Comment by andrey-qlogic** [comment]
@frankyn , thanks for the explanation.
